// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabularyApp.Data;

#nullable disable

namespace VocabularyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("VocabularyApp.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kanji")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("VocabularyApp.Models.VocabularyTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrongCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId")
                        .IsUnique();

                    b.ToTable("VocabularyTestResults");
                });

            modelBuilder.Entity("VocabularyApp.Models.VocabularyTestResult", b =>
                {
                    b.HasOne("VocabularyApp.Models.Vocabulary", "Vocabulary")
                        .WithOne("TestResult")
                        .HasForeignKey("VocabularyApp.Models.VocabularyTestResult", "VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("VocabularyApp.Models.Vocabulary", b =>
                {
                    b.Navigation("TestResult");
                });
#pragma warning restore 612, 618
        }
    }
}
